### PR TITLE
Added MySQL support

### PR DESCRIPTION
**Pull request by corpsee**
Added MySQL support.

P.S.: I couldn't do a normal healthcheck for MySQL container and added hack with sleep before php-censor installation.

### CODE REVIEW

**Comment by ketchoop** [comment]
@corpsee Oh, yeah, I know about this problem. There are two ways to work this problem out. But I think sleep for 20s in the entrypoint is not a good idea. You can do a health check like it has been done in Pgsql. For example you can check that the database dirs are existing:
```
test: ["CMD", "test", "-d", "/var/lib/mysql/$$MYSQL_DATABASE"]
```

**Comment by corpsee** [comment]
Thank you, I will try it

**Comment by corpsee** [comment]
@ket4yii I updated request. My solution for MySQL heathcheck is not the best, but it works :smiling_imp:

**Comment by ketchoop** [comment]
Could you rewrite it by compose [extends](https://docs.docker.com/compose/extends/)? Exmaple: inherit from docker-compose.yml which is standard and use Pgsql and reassign db service.

**Comment by ketchoop** [comment]
Also, about your solution: don't pay attention on it). I can rewrite it in a better way if I've got time.

**Comment by corpsee** [comment]
I will read about compose extends and will try to rewrite soon. Thanks.

**Comment by corpsee** [comment]
@ket4yii Done. I reworked compose files with layers (extends).

**Comment by ketchoop** [comment]
@corpsee sorry, this is not what I expected. I meant usage of extends in compose file. But I think you had problems with it because of healthchecks in compose.yml. I'm gonna place it to container. Anyway, please, do not delete your branch. I'll just take your code, make some changes and merge it manually. Ok?

P.S. Sorry for my late. We've got a lot of issues with migrating to new servers, so I just haven't got any time to work this issue out.

**Comment by corpsee** [comment]
Ok, thanks.

**Comment by ketchoop** [comment]
@corpsee  Added. But I couldn't cherry-pick some of your commits. But reference to you in a commit:). Thank you.

**Comment by corpsee** [comment]
Ок)

**Pull request closed without merging**
